### ISSUE TITLE
검색에서 (space) + \ 입력시 에러

### ISSUE THREAD

**Issue by Soarts** [realmani0/teacher_Viewer#1]
![- -](https://cloud.githubusercontent.com/assets/20292746/20659412/ce0eb616-b586-11e6-9ae1-0c824fa391f7.jpg)

검색에서 (space) 입력 후 \를 입력하면 발생하는 에러입니다.

**Comment by realmani0** [comment]
수정 처리 완료 - 배포함
테스트 필요

**Comment by Soarts** [comment]
검색 기능 단위 테스트 완료하였습니다.
