### ISSUE TITLE
[미래엔] 한쪽보기/양쪽보기 → 콘텐츠 팝업 학습 후 이북 회귀시 교과서 보기 유지 

### ISSUE THREAD

**Issue by hi763** [realmani0/teacher_Viewer#3]
1. 뷰어 한쪽보기/양쪽보기
2. 한쪽 보기 실행 후 버튼 클릭하여 학습 콘테를 띄움 → 학습 후 교과서 이북 보기로 회귀 → 회귀 후 교과서가 한쪽보기 그대로 남아 있어야 함
3. 현재는 회귀하면 이북이 새로고침이 되면서 양쪽 보기로 바뀜
4. 한쪽 보기면 한쪽 보기로 , 양쪽 보기면 양쪽 보기로 그대로 남아 있어야 함

**Comment by spvog** [comment]
1. 한쪽보기/양쪽보기 상태(PAGE_MODE) localStorage에 저장
2. ui에서 회귀할 때 viewer쪽에 전달할 값 필요(혹은 localStorage에 저장되어 있는 값 사용)

**Comment by realmani0** [comment]
수정된 버전 파일로 dong 책임에게 전달 완료
